config/routes.rb
Rails.application.routes.draw do
  
  get 'analysis/deanlist', to: 'analysis#deanlist'

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, param: :username do
    member do
      get 'dashboard'
    end
  end

  resources :analysis
  resources :prediction
  resources :enrollments
  resources :students
  resources :academic_year_semesters
  resources :courses, param: :code

  root 'welcome#index'









end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    
    # user only manage information that he owns.
    can :manage, User do |u|
        u.id == user.id
    end
   
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/academic_year.rb
class AcademicYear < ActiveRecord::Base
	has_many :academic_year_semesters
  	has_many :semesters, through: :academic_year_semesters
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :lecturer
  belongs_to :course
end

app/models/bachelor.rb
class Bachelor < ActiveRecord::Base
	has_many :departments
	has_many :students, through: :departments
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :department
  belongs_to :course_component

  has_many :enrollments
  has_many :students, through: :enrollments

  has_many :appointments
  has_many :lecturers, through: :appointments

  def to_param
  	code
  end
end

app/models/course_component.rb
class CourseComponent < ActiveRecord::Base
  has_many :courses

  has_many :spis
  has_many :departments, through: :spis
end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :students
	has_many :courses
	belongs_to :bachelor

	has_many :spis
	has_many :course_components, through: :spis
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
  belongs_to :grade
  belongs_to :academic_year_semester

  validates :student, :course, :grade, :academic_year_semester_id, presence: true
end

app/models/grade.rb
class Grade < ActiveRecord::Base
	has_many :enrollments
end

app/models/lecturer.rb
class Lecturer < ActiveRecord::Base
	has_many :appointments
	has_many :courses, through: :appointments
end

app/models/semester.rb
class Semester < ActiveRecord::Base
	has_many :academic_year_semesters
  	has_many :academic_years, through: :academic_year_semesters
end

app/models/spi.rb
class Spi < ActiveRecord::Base
  belongs_to :department
  belongs_to :course_component
end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :department
	has_one :user

	# dependent :destroy - when we destroy the student, the enrollments will be 
	# destroyed as well
	has_many :enrollments, dependent: :destroy 
  	has_many :courses, through: :enrollments
  	has_many :academic_year_semesters, -> { distinct }, through: :enrollments

  	accepts_nested_attributes_for :enrollments, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  belongs_to :student

  # allows to create, update and destroy student attributes.
  accepts_nested_attributes_for :student

  def to_param
  	username
  end
end
	

app/controllers/analysis_controller.rb
class AnalysisController < ApplicationController
	before_action :authenticate_user!

  	def index
  	end

  	def show
  	end

  	def deanlist
	  	# @session = AcademicYearSemester.find_by_id(params[:id]) || AcademicYearSemester.last
      @session = AcademicYearSemester.last(2).first
			@students = Student.joins(:enrollments).where(enrollments: {academic_year_semester_id: @session.id}).uniq
      @bachelors = Bachelor.all
  	end
end

app/helpers/analysis_helper.rb
module AnalysisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/prediction_helper.rb
module PredictionHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/analysis/deanlist.html.erb
<h3>Dean List</h3>
<br>

<!-- <%#= form_tag analysis_deanlist_path, method: :get, class: "form-horizontal", enforce_utf8: false  do %>
  	<div class="form-group">
      	<div class="col-md-8 col-xs-12 col-md-offset-2">
          	<%#= select_tag :id, options_from_collection_for_select(AcademicYearSemester.all, :id, :virtual_name), {prompt: "Please select the Academic Session", class: 'form-control', :onchange => "this.form.submit();"} %>
      	</div>
  	</div>
<%# end %>
 -->

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4><span class="label label-info"><strong><%= @session.academic_year.name %> / <%= @session.semester.name %></strong></span></h4>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="suggestion">
                        <thead>
                        	<tr>
                        		<th>Student</th>
                        		<th>Bachelor</th>
                        		<th>Department</th>
                        		<th>GPA</th>
                        	</tr>
                        </thead>
                        <tbody>
                        <% @students.each do |student| %>
                        	<% student_enrollments = student.enrollments.where(academic_year_semester: @session) %>
                        	<% gpa_included_enrollments = student_enrollments.where.not("grade_id = ? OR course_id IN (?) OR completed = ?", 8, [22, 40, 42, 43], false) %>
                        	<% gpa = gpa_included_enrollments.inject(0) { |sum, p| sum + p.grade.points * p.course.ch } %>
							<% ch = gpa_included_enrollments.inject(0) { |sum, p| sum + p.course.ch } %>
							<% student_gpa = (gpa/ch).round(2) if ch != 0 %>

							<% if student_gpa != nil && student_gpa >= 3.70  %>
                            <% if student == current_user.student %>
                                <tr class="success">
                            <% else %>
	                        	<tr>
                            <% end %>
	                        		<th><%= student.name %></th>
	                        		<th><%= student.department.bachelor.name %></th>
	                        		<th><%= student.department.name %></th>
	                        		<th><%= student_gpa %></th>
	                        	</tr>
	                        <% end %>
                        <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/analysis/index.html.erb
<h3>Academic Analysis</h3>
<br>

<%= link_to "Dean List", analysis_deanlist_path %>

<br>
<br>
Batch Performance.
<br>
<%= image_tag "analysis/batch.png", class: "img-responsive", alt: "" %> 
<br>
The Performance Trends of the first class honours students of the respective batches.
<%= image_tag "analysis/first_class_performance.png", class: "img-responsive", alt: "" %><br>
The Overall Performance Trends of the first class honours students.
<br>
<%= image_tag "analysis/first_class_trend.png", class: "img-responsive", alt: "" %> 