config/routes.rb
Rails.application.routes.draw do
  
  get 'analysis/deanlist', to: 'analysis#deanlist'

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, param: :username do
    member do
      get 'dashboard'
    end
  end

  resources :analysis
  resources :prediction
  resources :enrollments
  resources :students
  resources :academic_year_semesters
  resources :courses, param: :code

  root 'welcome#index'









end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    
    # user only manage information that he owns.
    can :manage, User do |u|
        u.id == user.id
    end
   
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/academic_year.rb
class AcademicYear < ActiveRecord::Base
	has_many :academic_year_semesters
  	has_many :semesters, through: :academic_year_semesters
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :lecturer
  belongs_to :course
end

app/models/bachelor.rb
class Bachelor < ActiveRecord::Base
	has_many :departments
	has_many :students, through: :departments
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :department
  belongs_to :course_component

  has_many :enrollments
  has_many :students, through: :enrollments

  has_many :appointments
  has_many :lecturers, through: :appointments

  def to_param
  	code
  end
end

app/models/course_component.rb
class CourseComponent < ActiveRecord::Base
  has_many :courses

  has_many :spis
  has_many :departments, through: :spis
end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :students
	has_many :courses
	belongs_to :bachelor

	has_many :spis
	has_many :course_components, through: :spis
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
  belongs_to :grade
  belongs_to :academic_year_semester

  validates :student, :course, :grade, :academic_year_semester_id, presence: true
end

app/models/grade.rb
class Grade < ActiveRecord::Base
	has_many :enrollments
end

app/models/lecturer.rb
class Lecturer < ActiveRecord::Base
	has_many :appointments
	has_many :courses, through: :appointments
end

app/models/semester.rb
class Semester < ActiveRecord::Base
	has_many :academic_year_semesters
  	has_many :academic_years, through: :academic_year_semesters
end

app/models/spi.rb
class Spi < ActiveRecord::Base
  belongs_to :department
  belongs_to :course_component
end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :department
	has_one :user

	# dependent :destroy - when we destroy the student, the enrollments will be 
	# destroyed as well
	has_many :enrollments, dependent: :destroy 
  	has_many :courses, through: :enrollments
  	has_many :academic_year_semesters, -> { distinct }, through: :enrollments

  	accepts_nested_attributes_for :enrollments, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  belongs_to :student

  # allows to create, update and destroy student attributes.
  accepts_nested_attributes_for :student

  def to_param
  	username
  end
end
	

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    load_and_authorize_resource

	def index
	end

    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        
        if @user.save
            # success
            UserNotifier.signup_email(@user).deliver
            flash[:success] = "Your account has been successfully created"
            redirect_to dashboard_user_path(@user.username)
        else
            # fail
            flash[:danger] = "Please try again"
            redirect_to new_user_path
        end
    end

    def dashboard
        @current_student = current_user.student
        @academic_sessions = @current_student.academic_year_semesters.order('id DESC')
        @course_components = CourseComponent.all

        student_enrollments = @current_student.enrollments

        @completed_enrollments = student_enrollments.where(completed: true)
        @incompleted_enrollments = student_enrollments.where(completed: false)

        @cgpa_excluded_enrollments = @completed_enrollments.where("grade_id = ? OR course_id IN (?)", 8, [22, 40, 42, 43])
        @cgpa_included_enrollments = @completed_enrollments - @cgpa_excluded_enrollments
        # find_by method finds the first record, hence not applicable
        # @last_completed_enrollment = Enrollment.where(student_id: student_id, completed: true).last
        # @enrollments = Enrollment.all.where(academic_year_semester_id: 1, student_id: student_id, completed: true)
    end

    def fulfillment
    end

    def enrollment
    end

    def course
    end

    def analysis
    end

    private
        def user_params
            params.require(:user).permit(:username, :email, :password, :password_confirmation, student_attributes: [:id, :name, :matric_no, :academic_year_id, :department_id])
        end
end

app/helpers/analysis_helper.rb
module AnalysisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/prediction_helper.rb
module PredictionHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/dashboard.html.erb
<h3>Dashboard</h3>

<br>
Student Name : <%= @current_student.name %>
<br>
Student Matric No : <%= @current_student.matric_no %>
<br>
Programme : <%= @current_student.department.bachelor.name %>
<br>
Student Department : <%= @current_student.department.name %>
<br>


<% gpa = @cgpa_included_enrollments.inject(0) { |sum, p| sum + p.grade.points * p.course.ch } %>
<% ch = @cgpa_included_enrollments.inject(0) { |sum, p| sum + p.course.ch } %>
Current CGPA : <strong><%= (gpa/ch).round(2) if ch != 0 %></strong>

<br>
<br>
Last Login: <%= l(current_user.last_sign_in_at, format: "%Y-%m-%-d %H:%M:%S") %>

<br>

<div class="container">
    <div class="row">
        <div class="col-xs-11">
            <h3>SPI : </h3> 
        </div>
        <a href="#portfolioModal1" class="btn btn-default col-xs-1" data-toggle="modal">
            <span class="glyphicon glyphicon-info-sign center-block" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="Grading scheme"></span>
        </a>
    </div>
    <div class="row">
        <% @course_components.each_with_index do |component, index| %>
        <div class="col-md-1 col-sm-2 col-xs-3 text-center" data-toggle="tooltip" data-placement="bottom" title="<%= component.name %>" >
            <% required_ch = Spi.find_by(department_id: @current_student.department_id, course_component_id: component.id).required_ch %>
            <% earned_ch = @current_student.courses.where(course_component_id: component.id).inject(0) { |sum, c| sum += c.ch } %>
            <% if earned_ch == required_ch %>
                <button class="btn btn-success btn-block active" type="button">
            <% elsif earned_ch > required_ch %>
                <button class="btn btn-warning btn-block active" type="button">
            <% else %>
                <button class="btn btn-danger btn-block active" type="button">
            <% end %>
                <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
                <span class="badge"><%= earned_ch %></span>
            </button>
            <div>
                <h5><%= component.code %></h5>
            </div>
        </div>
        <% end %>
    </div>
</div>


<br>



<%= link_to 'New Enrollment', new_enrollment_path %>
<br>
<br>

<%#= @last_completed_enrollment.inspect %>

<!-- Previous Semester : <%#= @last_completed_enrollment.academic_year_semester.academic_year.name %>,  <%#= @last_completed_enrollment.academic_year_semester.semester.name %> -->

<% @academic_sessions.each_with_index do |session, index| %>
    <% incompleted_enrollments = @incompleted_enrollments.where(academic_year_semester_id: session.id) %>
    <!-- grade_id = nil is not taken into consideration because -->
    <!-- the goals set do have grades. -->

    <% if index == 0 %>
        <!-- if completed = FALSE -->
        <!-- # show only if the enrollments are NOT completed-->
        <div><b>Current Semester</b></div>
        <br>
    <% end %>

    <!-- show only if session has enrollments as well as both academic_year and semester -->
    <% if session.academic_year_id != nil && session.semester_id != nil && incompleted_enrollments != [] %>
        <div><%= session.academic_year.name %>, <%= session.semester.name %>
        <div class="pull-right"><%= link_to 'Edit', edit_enrollment_path(session.id) %></div>
        </div>

            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Course Code</th>
                            <th>Course Name</th>
                            <th>Credit Hours</th>
                            <th>Grade</th>
                            <th>Grade Points</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% incompleted_enrollments.each_with_index do |e, i| %>
                        <tr class="warning">
                            <td><%= i+1 %></td>
                            <td><%= e.course.code %></td>
                            <td><%= e.course.name %></td>
                            <td><%= e.course.ch %></td>
                            <td><% if e.grade != nil %><%= e.grade.name %><% end %></td>
                            <td><% if e.grade != nil %><%= e.grade.points %><% end %></td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
    <% end %>
<% end %>


<% @academic_sessions.each_with_index do |session, index| %>
    <% completed_enrollments = @completed_enrollments.where(academic_year_semester_id: session.id) %>

    <% total_gpa = completed_enrollments.inject(0) { |sum, p| p.grade.points != nil ? sum + p.grade.points * p.course.ch : sum } %>
    <% total_ch = completed_enrollments.inject(0) { |sum, p| sum + p.course.ch } %>

    <% completed_cgpa_included_enrollments = completed_enrollments - @cgpa_excluded_enrollments %>
    <% final_gpa = completed_cgpa_included_enrollments.inject(0) { |sum, p| sum + p.grade.points * p.course.ch } %>
    <% final_ch = completed_cgpa_included_enrollments.inject(0) { |sum, p| sum + p.course.ch } %>

    <% if index == 0 %>
        <!-- if completed = TRUE -->
        <!-- # show only if the enrollments are completed-->
        <div><b>Previous Semesters</b></div>
        <br>
    <% end %>

    <!-- show only if session has enrollments as well as both academic_year and semester -->
    <% if session.academic_year_id != nil && session.semester_id != nil && completed_enrollments != [] %>
        <div><%= session.academic_year.name %>, <%= session.semester.name %>
        <div class="pull-right"><%= link_to 'Edit', edit_enrollment_path(session.id) %></div>
        </div>

            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Course Code</th>
                            <th>Course Name</th>
                            <th>Credit Hours</th>
                            <th>Grade</th>
                            <th>Grade Points</th>
                            <th>GPA</th>
                        </tr>
                    </thead>
                    <tbody>
                    	<% completed_enrollments.each_with_index do |e, i| %>
                        <% if @cgpa_excluded_enrollments.exists?(id: e.id) %>
                            <tr class="active">
                        <% else %>
                    	   <tr class="success">
                        <% end %>
                    		<td><%= i+1 %></td>
                    		<td><%= e.course.code %></td>
                    		<td><%= e.course.name %></td>
                    		<td><%= e.course.ch %></td>
                    		<td><%= e.grade.name %></td>
                    		<td><%= e.grade.points != nil ? e.grade.points * e.course.ch : "-" %></td>
                            <td></td>
                    	</tr>
                        <% end %>
                        <tr class="info">
                            <td colspan="3"><div class="text-right"><strong>Total</strong></div></td>
                            <td><%= total_ch %></td>
                            <td></td>
                            <td><%= total_gpa %></td>
                            <td><strong><%= (final_gpa/final_ch).round(2) if final_ch != 0 %></strong></td>
                        </tr>
                    </tbody>
                </table>
            </div>
    <% end %>
<% end %>

<div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <!-- Project Details Go Here -->
                        <h2>Grading Scheme</h2>
                        <p class="item-intro text-muted">University of Malaya<br>Last Updated : 2010</p>
                        <%= image_tag "university/um_grading_scheme.png", class: "img-responsive img-centered", alt: "" %>
                        <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
Hello!

<%= link_to 'Sign Up', new_user_path %>


app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>

<table>
    <tr>
        <td><%= f.label :username %></td>
        <td><%= f.text_field :username %></td>
    </tr>
    <tr>
        <td><%= f.label :email %></td>
        <td><%= f.text_field :email %></td>
    </tr>
    <tr>
        <td><%= f.label :password %></td>
        <td><%= f.text_field :password %></td>
    </tr>
    <tr>
        <td><%= f.label :password_confirmation %></td>
        <td><%= f.text_field :password_confirmation %></td>
    </tr>



    <!-- student details -->
    <%= f.fields_for :student do |student| %>
        <tr>
            <td><%= student.label :name %></td>
            <td><%= student.text_field :name %></td>
        </tr>
        <tr>
            <td><%= student.label :matric_no %></td>
            <td><%= student.text_field :matric_no %></td>
        </tr>
        <tr>
            <td><%= student.label :department_id %></td>
            <td><%= student.text_field :department_id %></td>
        </tr>
    <% end %>



    <tr>
        <td></td>
        <td><%= f.submit "Sign Up" %></td>
    </tr>
</table>

<% end %>


<%= @user.inspect %>
<br>
<%= @user.student.inspect %>   

app/views/users/show.html.erb
<%= @user.inspect %>