config/routes.rb
Rails.application.routes.draw do
  
  get 'analysis/deanlist', to: 'analysis#deanlist'

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, param: :username do
    member do
      get 'dashboard'
    end
  end

  resources :analysis
  resources :prediction
  resources :enrollments
  resources :students
  resources :academic_year_semesters
  resources :courses, param: :code

  root 'welcome#index'









end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    
    # user only manage information that he owns.
    can :manage, User do |u|
        u.id == user.id
    end
   
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/academic_year.rb
class AcademicYear < ActiveRecord::Base
	has_many :academic_year_semesters
  	has_many :semesters, through: :academic_year_semesters
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :lecturer
  belongs_to :course
end

app/models/bachelor.rb
class Bachelor < ActiveRecord::Base
	has_many :departments
	has_many :students, through: :departments
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :department
  belongs_to :course_component

  has_many :enrollments
  has_many :students, through: :enrollments

  has_many :appointments
  has_many :lecturers, through: :appointments

  def to_param
  	code
  end
end

app/models/course_component.rb
class CourseComponent < ActiveRecord::Base
  has_many :courses

  has_many :spis
  has_many :departments, through: :spis
end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :students
	has_many :courses
	belongs_to :bachelor

	has_many :spis
	has_many :course_components, through: :spis
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
  belongs_to :grade
  belongs_to :academic_year_semester

  validates :student, :course, :grade, :academic_year_semester_id, presence: true
end

app/models/grade.rb
class Grade < ActiveRecord::Base
	has_many :enrollments
end

app/models/lecturer.rb
class Lecturer < ActiveRecord::Base
	has_many :appointments
	has_many :courses, through: :appointments
end

app/models/semester.rb
class Semester < ActiveRecord::Base
	has_many :academic_year_semesters
  	has_many :academic_years, through: :academic_year_semesters
end

app/models/spi.rb
class Spi < ActiveRecord::Base
  belongs_to :department
  belongs_to :course_component
end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :department
	has_one :user

	# dependent :destroy - when we destroy the student, the enrollments will be 
	# destroyed as well
	has_many :enrollments, dependent: :destroy 
  	has_many :courses, through: :enrollments
  	has_many :academic_year_semesters, -> { distinct }, through: :enrollments

  	accepts_nested_attributes_for :enrollments, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  belongs_to :student

  # allows to create, update and destroy student attributes.
  accepts_nested_attributes_for :student

  def to_param
  	username
  end
end
	

app/helpers/analysis_helper.rb
module AnalysisHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/prediction_helper.rb
module PredictionHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pointa</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Custom Fonts -->
  <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='http://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
</head>

<body>
  
  <nav class="navbar navbar-default navbar-fixed" role="navigation" id="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Pointa</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li><%= link_to 'Dashboard', dashboard_user_path(current_user.username) %></li>
          <!-- else -->
          <!-- redirect_to fulfillment section on the landing page/ something else -->
          
          <li><%= link_to 'Enrollment', new_enrollment_path %></li>
          <li><%= link_to 'Course', courses_path %></li>
          <li><%= link_to 'Analysis', analysis_index_path %></li>
          <% end %>
          <% if user_signed_in? %>
            <li><%= link_to 'Logout', destroy_user_session_path , method: :delete %></li>
          <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <div class="row">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{name} alert-warning" %>
      <% end %>
    </div>
  </div>

  <div class="container" id="content">
    <%= yield %>
  </div>

 <!--  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="row">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{name}" %>
      <% end %>
    </div>
  </div>
 -->

</body>
</html>



app/views/user_notifier/signup_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Thanks for signing up, <%= @user.username %>!</h1>
    <p>Thanks for joining and have a great day! Now sign in and do awesome things!</p>
  </body>
</html>

app/views/user_notifier/signup_email.text.erb
Thanks for signing up, <%= @user.username %>!
Thanks for joining and have a great day! Now sign in and do awesome things!